-- 기존 테이블이 있다면 삭제하고 새 구조로 생성 (초기 개발용)
DROP TABLE IF EXISTS public.contents;

CREATE TABLE public.contents (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    
    -- 기본 정보
    title TEXT NOT NULL,                   -- 제목(가제)
    author_name TEXT NOT NULL,             -- 제작인원(이름)
    
    -- 기획안 상세 내용 (직접 사이트에서 작성하는 항목)
    keywords TEXT,                         -- 키워드
    intent TEXT,                           -- 기획의도
    target_date TEXT,                      -- 취재일정/일시
    deadline TEXT,                         -- 데드라인
    content_body TEXT,                     -- 상세 내용(발행 포맷 등 추가 기재 사항)
    
    -- 구글 Docs 등 외부 링크 (기존 방식 공존)
    proposal_url TEXT,                     -- 구글 Docs 링크 (위 양식을 안 쓰고 url만 적어도 되게 nullable)
    description TEXT,                      -- 추가 코멘트
    final_url TEXT,                        -- 완성본 링크
    
    -- 상태 관리
    status TEXT DEFAULT 'pending' NOT NULL,
    feedback_comment TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 누구나 자유롭게 CRUD 할 수 있도록 RLS 비활성화
ALTER TABLE public.contents DISABLE ROW LEVEL SECURITY;
